/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lizw_media_MediaRecorder */

#ifndef _Included_com_lizw_media_MediaRecorder
#define _Included_com_lizw_media_MediaRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lizw_media_MediaRecorder
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lizw_media_MediaRecorder_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_lizw_media_MediaRecorder
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lizw_media_MediaRecorder_start
  (JNIEnv *, jobject);

/*
 * Class:     com_lizw_media_MediaRecorder
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lizw_media_MediaRecorder_native_1setup
  (JNIEnv *, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
